#!/bin/bash
# apt-iq - An install queue system for apt-get.
# usage: apt-iq [aptgetargs].
#        apt-iq --nosep [aptgetargs]
# Run with --nosep to NOT split off and free the terminal.
if [ $1 == '--nosep' ]; then
  while :; do
    lsof /var/lib/dpkg/lock >/dev/null 2>&1
    [ ! $? = 0 ] && break
    sleep .01
  done
  apt-get ${@:2} -y -qq
  echo "DONE."
else
  $0 --nosep $@ &
fi